version: "3"
services:
  web:
    build: .
    ports:
      - 8000:8000
      - 37701:37701
    volumes:
      - .:/var/www/app
    environment:
      - ENABLE_GATSBY_REFRESH_ENDPOINT=true
    command: "npm run develop"
