backend:
  name: github
  branch: main
  repo: Ohana-France/gab-beaupuits
  commit_messages:
    create: "Création {{collection}} “{{slug}}”"
    update: "Mise à jour {{collection}} “{{slug}}”"
    delete: "Suppresion {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Suppression “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
locale: 'fr'

collections:
  - name: "galerie"
    label: "Galerie"
    folder: "src/pages/galerie"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "/static/img/galerie/{{folder}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "galerie-post",
        }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Dossier principal", name: "folder", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - label: "Image principale"
        name: "featuredimage"
        widget: "image"
      - label: "Images"
        name: "images"
        widget: "list"
        collapsed: true
        summary: '{{fields.image}}'
        field: { name: "image", widget: "image" }
      - { label: "Post associé (optionnel)", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "home"
    label: "Accueil"
    files:
      - file: "src/pages/index.md"
        label: "Actus"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Titre, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "URL Panneau Pocket", name: panneauPocketUrl, widget: string }
  - name: "pages"
    label: "Pages"
    files:
      - name: "commune"
        file: "src/pages/commune/index.md"
        label: "Commune"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string"  }
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "contact"
        file: "src/pages/contact/index.md"
        label: "Contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string"  }
          - { label: "Body", name: "body", widget: "markdown" }
    
      - file: "src/pages/infos-pratiques/index.md"
        label: "Infos pratiques"
        name: "infos-pratiques"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }